# Generated by Django 5.2.16 on 2026-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name="посилання на партнера (не обов'язково)")),
                ('img', models.ImageField(blank=True, null=True, upload_to='service_proposal/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Партнери',
                'verbose_name_plural': 'Партнери',
            },
        ),
    ]
