# Generated by Django 5.2.16 on 2026-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0002_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='adress_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='text_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
