# Generated by Django 5.2.16 on 2026-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0003_contactpage_adress_en_contactpage_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='text_under_logo',
            field=models.TextField(blank=True, editable=False, verbose_name='Текст під лого в футере'),
        ),
    ]
