# Generated by Django 5.2.16 on 2026-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0004_contactpage_text_under_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='text_under_logo_en',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
