# Generated by Django 5.2.16 on 2026-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0005_contactpage_text_under_logo_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='text_under_logo',
            field=models.TextField(blank=True, verbose_name='Текст під лого в футере'),
        ),
    ]
