# Generated by Django 5.2.16 on 2026-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0006_alter_contactpage_text_under_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='adress_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='text_under_logo_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
