# Generated by Django 5.2.16 on 2026-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0007_alter_contactpage_adress_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='text_slogan',
            field=models.TextField(blank=True, verbose_name='Текст слоган'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='text_slogan_en',
            field=models.TextField(blank=True),
        ),
    ]
