# Generated by Django 5.2.16 on 2026-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title', models.CharField(max_length=300, verbose_name='Початок текста')),
                ('description', models.TextField(verbose_name='Основний опис')),
                ('img', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Сторінка "Про нас"',
                'verbose_name_plural': 'Сторінка "Про нас"',
            },
        ),
        migrations.CreateModel(
            name='OurTeamAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото')),
                ('name_surname', models.CharField(max_length=200, verbose_name="Ім'я та прізвище")),
                ('profession', models.CharField(max_length=200, verbose_name='Посада')),
                ('begin_text', models.TextField(verbose_name='Короткий опис (видно одразу)')),
                ('description', models.TextField(verbose_name='Повний опис (розкривається по кліку "Дізнатись більше")')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Учасник команди',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
            },
        ),
    ]
