# Generated by Django 5.2.16 on 2026-07-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Хто ми"', 'verbose_name_plural': 'Хто ми'},
        ),
    ]
