# Generated by Django 5.2.16 on 2026-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0003_alter_aboutpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='description_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='label_en',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_en',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='ourteamaboutpage',
            name='begin_text_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='ourteamaboutpage',
            name='description_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='ourteamaboutpage',
            name='profession_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
