# Generated by Django 5.2.16 on 2026-07-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_delete_pointservicepage'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
