# Generated by Django 5.2.16 on 2026-07-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_servicepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
