# Generated by Django 5.2.16 on 2026-07-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistsServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text_begin', models.TextField(verbose_name='Короткий опис (видно одразу)')),
                ('conditions', models.CharField(max_length=300, verbose_name='Умови (наприклад "15-20% від пакета, не більше $3000")')),
                ('description', models.TextField(verbose_name='Розгорнутий опис (розкривається по кліку)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Блок послуг',
                'verbose_name_plural': 'Блоки послуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistsPointServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_points', to='service_page.specialistsservicepage', verbose_name='Блок послуг')),
            ],
            options={
                'verbose_name': 'Пункт (послуг)',
                'verbose_name_plural': 'Пункти (послуг)',
                'ordering': ['order'],
            },
        ),
    ]
