# Generated by Django 5.2.16 on 2026-07-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Послуги',
                'verbose_name_plural': 'Послуги',
            },
        ),
        migrations.CreateModel(
            name='PointServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_points', to='service_page.servicepage', verbose_name='Блок співпраці')),
            ],
            options={
                'verbose_name': 'Пункт (Послуги)',
                'verbose_name_plural': 'Пункти (Послуги)',
            },
        ),
    ]
