# Generated by Django 5.2.16 on 2026-07-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0002_servicepage_pointservicepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistsservicepage',
            options={'ordering': ['order'], 'verbose_name': 'Рекрутинг', 'verbose_name_plural': 'Рекрутинг'},
        ),
    ]
