# Generated by Django 5.2.16 on 2026-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0003_alter_specialistsservicepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistsservicepage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Зображення'),
        ),
    ]
