# Generated by Django 5.2.16 on 2026-07-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0004_specialistsservicepage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProposalServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='service_proposal/', verbose_name='Зображення')),
                ('position', models.CharField(max_length=100, verbose_name='Мітка (наприклад "Оренда HR-менеджера")')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_text', models.TextField(verbose_name='Опис під заголовком')),
                ('price', models.CharField(blank=True, max_length=200, verbose_name='Умови/ціна')),
                ('text_begin', models.TextField(verbose_name='Розгорнутий текст (початок, "Що ви отримуєте")')),
                ('text_end', models.TextField(blank=True, verbose_name='Розгорнутий текст (кінець)')),
                ('title_main', models.CharField(max_length=200, verbose_name='Заголовок (для головної сторінки)')),
                ('text_main', models.TextField(verbose_name='Текст під заголовком (для головної сторінки)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Пропозиція послуги',
                'verbose_name_plural': 'Пропозиції послуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProposalPointServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_points', to='service_page.serviceproposalservicepage', verbose_name='Пропозиція послуги')),
            ],
            options={
                'verbose_name': 'Пункт (Послуги)',
                'verbose_name_plural': 'Пункти (Послуги)',
                'ordering': ['order'],
            },
        ),
    ]
