# Generated by Django 5.2.16 on 2026-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0005_serviceproposalservicepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='text_begin',
            field=models.TextField(blank=True, verbose_name='Розгорнутий текст (початок, "Що ви отримуєте")'),
        ),
    ]
