# Generated by Django 5.2.16 on 2026-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0006_alter_serviceproposalservicepage_text_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointservicepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='text_en',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceproposalpointservicepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='position_en',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='price_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='text_begin_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='text_end_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='text_main_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='title_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='title_main_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceproposalservicepage',
            name='title_text_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='specialistspointservicepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='specialistsservicepage',
            name='conditions_en',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='specialistsservicepage',
            name='description_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='specialistsservicepage',
            name='text_begin_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='specialistsservicepage',
            name='title_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
