# Generated by Django 5.2.16 on 2026-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0007_pointservicepage_text_en_servicepage_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointservicepage',
            name='text_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='text_en',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceproposalpointservicepage',
            name='text_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='position_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='price_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='text_begin_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='text_end_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='text_main_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='title_main_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceproposalservicepage',
            name='title_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialistspointservicepage',
            name='text_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='specialistsservicepage',
            name='conditions_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='specialistsservicepage',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialistsservicepage',
            name='text_begin_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialistsservicepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
