# Generated by Django 5.2.16 on 2026-07-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachCardHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaser_title', models.CharField(max_length=100, verbose_name='Заголовок картки')),
                ('teaser_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткий текст')),
                ('expanded_text_begin', models.TextField(blank=True, max_length=200, null=True, verbose_name='Розгорнутий текст (початок)')),
                ('expanded_text_end', models.TextField(blank=True, max_length=200, null=True, verbose_name='Розгорнутий текст (кінець)')),
            ],
            options={
                'verbose_name': 'Картка підходу',
                'verbose_name_plural': 'Картки підходу',
            },
        ),
        migrations.CreateModel(
            name='CollaborationHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок співпраці')),
                ('text', models.CharField(max_length=300, verbose_name='Текст співпраці')),
            ],
            options={
                'verbose_name': 'Блок співпраці',
                'verbose_name_plural': 'Блок співпраці',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=100, verbose_name='Заголовок головного банера')),
                ('hero_text', models.CharField(max_length=200, verbose_name='Інформація головного банера')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='IndustriesHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_position_title', models.CharField(max_length=100, verbose_name='Заголовок блоку індустрій')),
                ('flat_positon_text', models.TextField(verbose_name='Текст блоку індустрій')),
            ],
            options={
                'verbose_name': 'Блок індустрій',
                'verbose_name_plural': 'Блок індустрій',
            },
        ),
        migrations.CreateModel(
            name='ApproachCardPointHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='home_page.approachcardhomepage', verbose_name='Картка')),
            ],
            options={
                'verbose_name': 'Пункт картки підходу',
                'verbose_name_plural': 'Пункти картки підходу',
            },
        ),
        migrations.CreateModel(
            name='CollaborationPointHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_points', to='home_page.collaborationhomepage', verbose_name='Блок співпраці')),
            ],
            options={
                'verbose_name': 'Пункт (співпраці)',
                'verbose_name_plural': 'Пункти (співпраці)',
            },
        ),
        migrations.CreateModel(
            name='IndustriesFlatPointHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_points', to='home_page.industrieshomepage', verbose_name='Блок індустрій')),
            ],
            options={
                'verbose_name': 'Пункт (позиції)',
                'verbose_name_plural': 'Пункти (позиції)',
            },
        ),
        migrations.CreateModel(
            name='IndustriesJobPointHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_points', to='home_page.industrieshomepage', verbose_name='Блок індустрій')),
            ],
            options={
                'verbose_name': 'Пункт (вакансії)',
                'verbose_name_plural': 'Пункти (вакансії)',
            },
        ),
        migrations.CreateModel(
            name='PointServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_points', to='pages.servicepage', verbose_name='Блок співпраці')),
            ],
            options={
                'verbose_name': 'Пункт (послуг)',
                'verbose_name_plural': 'Пункти (послуг)',
            },
        ),
    ]
