# Generated by Django 5.2.16 on 2026-07-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approachcardhomepage',
            options={'verbose_name': 'Наш підхід', 'verbose_name_plural': 'Наш підхід'},
        ),
        migrations.AlterModelOptions(
            name='collaborationhomepage',
            options={'verbose_name': 'Умови співпраці', 'verbose_name_plural': 'Умови співпраці'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Рекрутинг для агробізнесу та суміжних галузей', 'verbose_name_plural': 'Рекрутинг для агробізнесу та суміжних галузей'},
        ),
        migrations.AlterModelOptions(
            name='industrieshomepage',
            options={'verbose_name': 'З ким і над чим ми працюємо', 'verbose_name_plural': 'З ким і над чим ми працюємо'},
        ),
    ]
