# Generated by Django 5.2.16 on 2026-07-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_approachcardhomepage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointServicePage',
        ),
    ]
