# Generated by Django 5.2.16 on 2026-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_delete_pointservicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='approachcardhomepage',
            name='expanded_text_begin_en',
            field=models.TextField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approachcardhomepage',
            name='expanded_text_end_en',
            field=models.TextField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approachcardhomepage',
            name='teaser_text_en',
            field=models.TextField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approachcardhomepage',
            name='teaser_title_en',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='approachcardpointhomepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='collaborationhomepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='collaborationhomepage',
            name='title_en',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='collaborationpointhomepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='industriesflatpointhomepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='industrieshomepage',
            name='flat_position_title_en',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='industrieshomepage',
            name='flat_positon_text_en',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='industriesjobpointhomepage',
            name='text_en',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
